
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package placaDeCarro;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int error = 1;
  public static final int PLACA = 7;
  public static final int MENOS = 4;
  public static final int IDENT = 6;
  public static final int EOF = 0;
  public static final int INTEIRO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTVIRG",
  "MAIS",
  "MENOS",
  "INTEIRO",
  "IDENT",
  "PLACA"
  };
}

